# Schema for the configuration files of the File module.

field.value.leaflet_edit:
  style:
    type: sequence
    label: Leaflet Style
    mapping:
      style_color:
        type: string
        label: 'Path color'
  style_map:
    type: sequence
    label: Style and attribute mapping
    mapping:
      mapping_color:
        type: string
        label: 'Mapping Path colr'
      query:
        type: sequence
        label: 'URL query key value pairs'
        sequence:
          type: string

