# Schema for the configuration files of the File module.

field.leaflet_edit:
  style:
    type: sequence
    label: Leaflet Style
    mapping:
      style_color:
        type: string
        label: 'Path colr'
  style_map:
    type: sequence
    label: Style and attribute mapping
    mapping:
      mapping_color:
        type: string
        label: 'Mapping Path colr'



